version: "3"
services:
 mongo-chat:
  image: mongo:4.2.5
  container_name: mongo-chat
  ports:
  - "27018:27017"
  environment:
    MONGO_INITDB_DATABASE: chat
  volumes:
   - ./resources/mongodb:/docker-entrypoint-initdb.d
