version: "3"
services:
 mongo-chat:
  image: mongo:4.2.5
  container_name: mongo-chat
  environment:
    MONGO_INITDB_DATABASE: chat
  volumes:
   - ./resources/mongodb:/docker-entrypoint-initdb.d

 chat:
  build: .
  container_name: chat
  ports:
    - "8080:8080"
  environment:
    MONGO_HOST: mongo-chat
  depends_on:
    - mongo-chat
